### ISSUE TITLE
Is it possible support anthropic API key instead of the Claude session key?

### ISSUE THREAD

**Issue by nasyxx** [mzacho/claudia#3]
Is it possible support anthropic API key instead of the Claude session key?

**Comment by mzacho** [comment]
I am not planning on buying access to the API as I'm already paying for Claude AI pro.

It looks like it wouldn't be too much work to add support for it though, I'd be open for a PR if you want to work on this :) However I think projects only exist in the claude.ai api, so files can't be added as project knowledge. Also, I don't think the api supports listing previous chats. So there's some refactoring to be done.

**Comment by nasyxx** [comment]
> However I think projects only exist in the claude.ai api,

Yes!  I didn't notice that until I went back to claude on the web, it actually mapped most of all those operations on claude.ai.
