### ISSUE TITLE
some custom varibales not set by use-package's custom directive

### ISSUE THREAD

**Issue by oatmealm** [mzacho/claudia#6]
When setting using use-package's :custom, some variables remain undeclared. i.e. `claudia-session-key` was set but `claudia-ignore-buffers-regexps` is void unless setq from :config.

```
claudia--claude-ai-request-get-projects: Symbol’s value as variable is void: claudia-organization-id
```

**Comment by mzacho** [comment]
Thanks for reporting this. Should be fixed by

a5a90bf * add custom var claudia-max-recent-buffers-content-length
e0a6194 * add custom var claude-organization-id

**Comment by oatmealm** [comment]
I see I paseted the wrong variable, but you noticed! it's indeed `claudia-organization-id` that's not set
